version: 2.1
executors:
  go:
    docker:
      - image: circleci/golang:1.11
    environment:
      - GO111MODULE: "on"

  bazel:
    docker:
      - image: l.gcr.io/google/bazel:0.21.0

commands:
  prepare_go:
    description: "Vendoring go modules with CircleCI caches"
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - v1-mod-{{ checksum "go.mod" }}
      - run:
          name: Vendoring
          command: go mod download
      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache

jobs:
  test:
    executor: go
    steps:
      - checkout
      - prepare_go
      - run:
          name: Run tests
          command: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Submit report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  bazeltest:
    executor: bazel
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bazel-test-cache-{{ .Branch }}-
            - v1-bazel-test-cache-master-
            - v1-bazel-test-cache-
      - run:
          name: Run test using bazel
          command: |
            bazel test --disk_cache=/tmp/bazeltest/ --features=race //...
      - save_cache:
          key: v1-bazel-test-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/bazeltest

  reviewdog:
    executor: go
    environment:
      - REVIEWDOG_VERSION: "0.9.11"
    steps:
      - checkout
      - prepare_go
      - run: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - run: go vet ./... 2>&1 | ./reviewdog -f=govet -reporter=github-pr-check

workflows:
  version: 2
  citest:
    jobs:
      - test
      - bazeltest
      - reviewdog:
          requires:
            - test
            - bazeltest
